azure:
  free_disk_space: true
  timeout_minutes: 360
  settings_linux:
    swapfile_size: 10GiB
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github_actions:
  self_hosted: true
provider:
  linux_64: github_actions
